In [23]:
import pandas as pd

# Population Analysis
Reading and merging the scraped country and region data.

In [31]:
countries = pd.read_csv("countries.csv")
regions = pd.read_csv("regions.csv")
countries.head()

,rank,country,population,yearly_change,net_change,density,land_area,migrants,fertility_rate,median_age,urban_pop,world_share
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","−440,456",1.93,29.2,37.6%,17.8%
1,2,China,"1,412,914,089",−0.22%,"−3,182,005",150,"9,388,211","−232,107",1.03,40.6,68.7%,17%
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","−39,472",2.08,30.7,60.3%,3.5%
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","−1,144,738",3.44,20.8,34.7%,3.1%

Checking whether any country names fail to match between the two CSVs before we merge them

In [32]:
countries_set = set(countries["country"])
regions_set = set(regions["country"])
countries_set - regions_set

{'Brunei',
 'Czech Republic (Czechia)',
 'Hong Kong',
 'Macao',
 'North Macedonia',
 'Saint Barthelemy',
 'Saint Kitts & Nevis',
 'Saint Pierre & Miquelon',
 'Sao Tome & Principe',
 'St. Vincent & Grenadines',
 'Turks and Caicos',
 'U.S. Virgin Islands',
 'Wallis & Futuna'}

Rename and merge

In [33]:
renames = {"Czech Republic (Czechia)": "Czechia",
    "Hong Kong": "China, Hong Kong SAR",
    "Macao": "China, Macao SAR",
    "North Macedonia": "Republic of North Macedonia",
    "Brunei": "Brunei Darussalam",
    "Saint Barthelemy": "Saint Barthélemy",
    "Saint Kitts & Nevis": "Saint Kitts and Nevis",
    "Saint Pierre & Miquelon": "Saint Pierre and Miquelon",
    "Sao Tome & Principe": "Sao Tome and Principe",
    "St. Vincent & Grenadines": "Saint Vincent and the Grenadines",
    "Turks and Caicos": "Turks and Caicos Islands",
    "U.S. Virgin Islands": "United States Virgin Islands",
    "Wallis & Futuna": "Wallis and Futuna Islands",
  }
for old_name, new_name in renames.items():
    countries.loc[countries["country"] == old_name, "country"] = new_name

Check: returns set() if everything is good

In [34]:
countries_set = set(countries["country"])
regions_set = set(regions["country"])
countries_set - regions_set

set()

# merge

In [35]:
data = pd.merge(countries, regions, on="country")
data.head()

,rank,country,population,yearly_change,net_change,density,land_area,migrants,fertility_rate,median_age,urban_pop,world_share,continent
0,1,India,"1,476,625,576",0.87%,"12,760,051",497,"2,973,190","−440,456",1.93,29.2,37.6%,17.8%,Asia
1,2,China,"1,412,914,089",−0.22%,"−3,182,005",150,"9,388,211","−232,107",1.03,40.6,68.7%,17%,Asia
2,3,United States,"349,035,494",0.51%,"1,759,687",38,"9,147,420","1,177,848",1.63,38.7,83.1%,4.2%,Northern America
3,4,Indonesia,"287,886,782",0.76%,"2,165,546",159,"1,811,570","−39,472",2.08,30.7,60.3%,3.5%,Asia
4,5,Pakistan,"259,299,791",1.6%,"4,080,237",336,"770,880","−1,144,738",3.44,20.8,34.7%,3.1%,Asia